source 'http://rubygems.org'
source 'http://gems.github.com'
ruby '2.2.2'

gem 'rake', '= 0.8.7'
gem 'libxml-ruby'
gem 'sqlite3'
gem 'sequel'
gem 'sinatra'
gem 'thin'
gem 'unicorn'
gem 'httpclient'
gem 'json'
gem 'crack'
gem 'ratom'
gem 'ruby-hmac'
gem 'eventmachine'
